### ISSUE TITLE
Warmed up flutter for web

### ISSUE THREAD

**Issue by DoumanAsh** [PlugFox/docker_flutter#10]
I wonder if you would be ok to introduce `flutter-warmed` wnich would prepare `flutter` image to web development by running:

```
flutter upgrade
flutter precache --no-ios --no-linux --no-windows --no-winuwp --no-macos --no-fuchsia --universal --web
```

This will be a good option for user to have flutter ready from start instead of waiting for image to build and download related tools
It will relatively fatten up docker image but this is expected in the same way as for android variant.

It is not a big deal though as I can prepare my own image based on yours, but I just wanted to suggest it as convenience

**Comment by PlugFox** [comment]
It's a good idea, I will gladly  ry to do it before the end of the year

If you want, you can make a pull request yourself.

**Comment by PlugFox** [comment]
Most size consumed by flutter_web_sdk, canvaskit and dart2js

![image](https://user-images.githubusercontent.com/7805176/148496456-787ec23f-2f4d-4850-aafc-6fb22ef79bd8.png)

**Comment by PlugFox** [comment]
That's good

```bash
RUN set -eux; flutter upgrade \
    && dart --disable-analytics \
    && flutter config --no-analytics --enable-web --no-enable-linux-desktop --no-enable-macos-desktop \
                      --no-enable-windows-desktop --no-enable-windows-uwp-desktop --no-enable-android \
                      --no-enable-ios --no-enable-fuchsia --no-enable-custom-devices \
    && flutter precache --web --no-universal --no-ios --no-linux --no-windows --no-winuwp --no-macos --no-fuchsia
```

![image](https://user-images.githubusercontent.com/7805176/148496970-c0d9a98e-f379-4e95-b40c-b2eecef4ec86.png)

**Comment by DoumanAsh** [comment]
> Most size consumed by flutter_web_sdk, canvaskit and dart2js
Nothing can be done about it

Yes, I did my best to make sure no trash is in there :)
And yeah these images should be perfectly ready to build for web immediately on download.

**Comment by PlugFox** [comment]
@DoumanAsh in this image I use `flutter precache --web --no-universal`, is that good idea?

**Comment by DoumanAsh** [comment]
@PlugFox Oh I didn't notice `--no-universal`
But in your case it seems it is enough, but I remember last time I was testing it on my flutter project it installed some extra deps (universal) before I could use flutter so I'm not sure

**Comment by PlugFox** [comment]
No problem, I need about half hour and all done)

**Comment by PlugFox** [comment]
# How to simple build project inside docker container:

```bash
docker run --rm -it -v ${PWD}:/project --workdir /project --user=root:root --name flutter_stable_web \
	plugfox/flutter:stable-web /bin/bash -c \
	"cd /project && flutter pub get && flutter pub run build_runner build && flutter build web --release"
```

**Comment by PlugFox** [comment]
# How to build and serve with docker swarm:

> ⚠️ BEWARE IN MY EXAMPLE I USE MONOREPO WITH SUBFOLDERS `shared` AND `client` ⚠️

### Create `./dockerfiles/site.dockerfile`
```dockerfile
# Prepare web release
FROM plugfox/flutter:stable-web AS build

# USER root
WORKDIR /home

# Copy app source code and compile it
COPY --chown=101:101 client client
COPY --chown=101:101 shared shared

RUN set -eux; \
    # Change directory to client for monorepo
    cd client \
    # Ensure packages are still up-to-date if anything has changed
    && flutter pub get \
    # Codegeneration
    && flutter pub run build_runner build --delete-conflicting-outputs --release \
    # Localization
    #&& flutter pub global run intl_utils:generate
    # Build web release (opt --tree-shake-icons)
    && flutter build web --release --no-source-maps \
        --pwa-strategy offline-first \
        --web-renderer auto --base-href /

# Production from scratch
FROM nginx:alpine as production

COPY --from=build --chown=101:101 /home/client/build/web /usr/share/nginx/html

# Expose server
EXPOSE 80/tcp
```

### Create `./site.compose.yml`
```dockerfile
version: '3.9'

services:
  site:
    hostname: my-site
    container_name: my-site
    image: registry.domain.tld/my-site
    restart: unless-stopped
    ports:
      - '80:80'
    build:
      context: ./
      dockerfile: dockerfiles/site.dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.10'
          memory: 64M
        limits:
          cpus: '0.25'
          memory: 256M
```

### Serve

`docker compose -f ./site.compose.yml up site`
