### ISSUE TITLE
web image version not found

### ISSUE THREAD

**Issue by itapai** [PlugFox/docker_flutter#15]
hi, 

currently the web image is available via the `stable-web` tag.
would it be possible to tag the web image with the flutter version as well ( i.e. `2.5.3-web`)?

**Comment by PlugFox** [comment]
@itapai current stable version of flutter - `2.8.1`, maybe better this?

**Comment by itapai** [comment]
That would be really helpful if you could run the pipeline for `2.5.3.-web`.
Thank you very much.

**Comment by PlugFox** [comment]
@itapai no problem, pipeline already runned.
After "BUILD AND PUBLISH TAG" you can use image.
https://github.com/PlugFox/docker_flutter/actions/runs/1682456667

Feel free response in closed issue.

**Comment by itapai** [comment]
ty for the tag :+1:

**Comment by PlugFox** [comment]
[2.5.3-web](https://hub.docker.com/layers/plugfox/flutter/2.5.3-web/images/sha256-44a2a260da65867a86756f252103febb49ea6dffc40c8b9b80ab05976f8a54b0?context=repo)
