### ISSUE TITLE
Publish 2.10.5?

### ISSUE THREAD

**Issue by DoumanAsh** [PlugFox/docker_flutter#20]
I know there is new 3.x verison, but considering how buggy flutter is, I think it would be nice to have latest 2.x version available as image

**Comment by PlugFox** [comment]
@DoumanAsh no problem, I'm already run the action.
Wait about ten minutes.

**Comment by DoumanAsh** [comment]
I appreciate, thank you

**Comment by PlugFox** [comment]
@DoumanAsh I send an invitation for you, accept that and you can build and deploy new releases.

**Comment by PlugFox** [comment]
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/7805176/168958641-e95a2d46-2542-41ac-9201-c956f6e1c4e2.png">

**Comment by DoumanAsh** [comment]
Yep, I got it, appreciate it :)

**Comment by DoumanAsh** [comment]
Also see it is already finished, issue can be closed

**Comment by PlugFox** [comment]
[2.10.5](https://hub.docker.com/r/plugfox/flutter/tags?page=1&name=2.10.5)
